name: dataengineer_job_scraper_etl

on:
  workflow_dispatch:
  push: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download spaCy model
        run: python -m spacy download en_core_web_lg
      
      - name: auth
        uses: google-github-actions/auth@v1
        with: 
          credentials_json: ${{ secrets.GCP_SECRET }}
          
      - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@v2
        with: 
          name: de_job_etl
          runtime: python38
          project_id: mybookdashboard
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/mybookdashboard/topics/de_job_etl
          timeout: 540
          memory_mb: 1024
