name: dataengineer_job_scraper_etl

on:
  
  workflow_dispatch:
  
  push: 
    branches: [ main ]
    paths:
    - "etl**"
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}  

   - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@v2
        with: 
          name: de_job_etl
          runtime: python38
          project_id: ornate-reef-332816
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/ornate-reef-332816/topics/de_job_etl
          source_dir: ./de_job_etl/
          timeout: 540
          memory_mb: 1024
        env:
          GCS_SERVICE_ACCOUNT_KEY: ${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}